name: Simulation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: lfenergy/arras:develop
    
    steps:
    - uses: actions/checkout@v3

    - name: Run simulation
      run: gridlabd main.glm
